# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: صفحه اصلی
    url: /
    weight: 10
  - name: نرم‌‌افزار اسکرچ
    url: "https://scratch.chatgptpeaz.ir/play"
    weight: 20
    target: "_blank"
